server:
  baseUrl: http://localhost:3000/
  imageUrl: images/
<<<<<<< HEAD
  imageServerDir : C:/Users/Admin/Documents/SE331-lab06/web/images
=======
>>>>>>> b04d23fe73bc31a48b6e25d53769cb18bf29ab8f
---
spring:
  profiles: local
server:
  baseUrl: http://localhost:1000/
<<<<<<< HEAD
  imageUrl: images/
  imageServerDir : C:/Users/Admin/Documents/SE331-lab07/web/images/
---
spring:
  profiles: remote
server:
  baseUrl: https://s3-ap-southeast-1.amazonaws.com/se331/
  imageUrl: pics/

=======
  imageUrl : images/
---
spring:
  profiles: pic
server:
  baseUrl: https://s3-ap-southeast-1.amazonaws.com/se331/
  imageUrl : pics/
>>>>>>> b04d23fe73bc31a48b6e25d53769cb18bf29ab8f
